### ISSUE TITLE
distutils package is deprecated

### ISSUE THREAD

**Issue by tripplehelix** [eMPee584/night-mode-daemon#1]
Python 3.10.7
Kernel: 5.19.0-2-amd64
OS: Debian GNU/Linux bookworm/sid
WM: Xfwm4
Shell: zsh 5.9

I was really excited for this, when settings is launched:

```
/usr/bin/night_mode_settings:4: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  import distutils.util
Traceback (most recent call last):
  File "/usr/bin/night_mode_settings", line 140, in <module>
    settings = SettingsWindow()
  File "/usr/bin/night_mode_settings", line 41, in __init__
    loadUi(os.path.join(os.path.dirname(os.path.realpath(__file__)), 'settings.ui'), self)
  File "/home/tom/.local/lib/python3.10/site-packages/PyQt5/uic/__init__.py", line 238, in loadUi
    return DynamicUILoader(package).loadUi(uifile, baseinstance, resource_suffix)
  File "/home/tom/.local/lib/python3.10/site-packages/PyQt5/uic/Loader/loader.py", line 66, in loadUi
    return self.parse(filename, resource_suffix)
  File "/home/tom/.local/lib/python3.10/site-packages/PyQt5/uic/uiparser.py", line 1020, in parse
    document = parse(filename)
  File "/usr/lib/python3.10/xml/etree/ElementTree.py", line 1222, in parse
    tree.parse(source, parser)
  File "/usr/lib/python3.10/xml/etree/ElementTree.py", line 569, in parse
    source = open(source, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/settings.ui'
```

When the daemon is launched:

```
/usr/bin/night_mode_daemon:6: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  import distutils.util
night_mode_daemon /home/tom/.config/night-mode.conf gives {} {}
night_mode_daemon config before reload: {} {}
Traceback (most recent call last):
  File "/usr/bin/night_mode_daemon", line 133, in <module>
    reload_config()
  File "/usr/bin/night_mode_daemon", line 55, in reload_config
    night_mode_enabled = distutils.util.strtobool(config['General']['nightModeEnabled'])
  File "/usr/lib/python3/dist-packages/configobj.py", line 554, in __getitem__
    val = dict.__getitem__(self, key)
KeyError: 'General'
```

**Comment by eMPee584** [comment]
I'm having a look at this.. the deprecation warning is not the problem though, the path to the settings.ui file is.. going to reproduce & fix over the weekend, regards..

**Comment by eMPee584** [comment]
.. does `ls -lah /usr/bin/night_mode_*` show that these are symlinks into `/usr/share/night_mode/`?

**Comment by eMPee584** [comment]
ah settings fails to find its UI file and doesn't write an initial configuration and the daemon doesn't cope with that. I should fix that and simplify the directory structure.. for now, you should be able to run from inside the `usr/share/night_mode` path in this repo which has three files `night_mode_daemon`, `night_mode_settings` and `settings.ui`
